#!/bin/bash
# Ask for version
echo "-- MeTools build script --"
echo "Please, enter the version number: "
read version
version="metools-$version"

# Create build/MeTools
rm -r -f build/MeTools
mkdir -p build/MeTools

# Copy in build/MeTools
cp -a --parents Config/ Console/ Controller/ Lib/ Locale/ita Model/ Utility/ \
Vendor/ View/ webroot/ CHANGELOG.md CHANGELOG_it.md COPYNG README.md README_it.md version build/MeTools

# Enter build/MeTools
cd build/MeTools

# Remove .directory files
find . -name ".directory" -type f -exec rm -rf {} \;

# Remove old files
find . -name "*.old.*" -type f -exec rm -rf {} \;

# Delete some uncompressed files
rm -f webroot/js/slugify.js

# Go back to build/
cd ../

# Create the tar archive
tar -czf $version.tar.gz MeTools/*
echo "The file $version.tar.gz was created"

exit 0